// Lexical

id           : 'a'-'z' {'a'-'z'}             ;
int64        : '1'-'9' {'0'-'9'}             ;
quotedstring : '"' . '"'                     ;
!whitespace  : ' '                           ;

equals      : '=' '=' ;
notequals   : '!' '=' ;
greaterthan : '>'     ;
lessthan    : '<'     ;

// Syntax

<<
import(
	"github.com/adammck/m9texp/ast"
	"github.com/adammck/m9texp/gen/token"
)
>>

Expression
  : Expression Operator Operand << ast.MakeBinaryExpression($0.(*ast.Expression), $2.(*ast.Operand), $1.(ast.Operator)) >>
  | Operand                     << ast.MakeUnaryExpression($0.(*ast.Operand)) >>
  ;     

Operand:
  : Variable            << ast.MakeOperand($0) >>
  | Str                 << ast.MakeOperand($0) >>
  | Int                 << ast.MakeOperand($0) >>
  | "(" Expression ")"  << ast.MakeOperand($1) >>
	;

Operator:
  : equals      << &ast.Equals{},      nil >>
  | notequals   << &ast.NotEquals{},   nil >>
  | greaterthan << &ast.GreaterThan{}, nil >>
  | lessthan    << &ast.LessThan{},    nil >>
  ;

Variable : id           << ast.MakeVariable($0.(*token.Token)) >> ;
Str      : quotedstring << ast.StrValue($0.(*token.Token)) >>     ;
Int      : int64        << ast.IntValue($0.(*token.Token)) >>     ;
